development:
  host: localhost
  adapter: postgresql
  database: messaging_development
  pool: 5
  timeout: 5000

test: &test
  host: localhost
  adapter: postgresql
  database: messaging_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: messaging_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
